---
  name: "Automated Testing"

  on:
    pull_request:
      branches:
        - main

  permissions:
    id-token: write
    contents: read

  jobs:
    call-terratest-workflow:
      uses: davivienda-colombia/davi-coe-workflow-terratest-pipeline/.github/workflows/reusable-azure-workflow.yml@v1.6.0
      with:
       go_version: "1.20"
       environment: "production"
      secrets:
        USER_GITHUB: ${{ secrets.DAVI_READER_GITHUB_USER }}
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SANDBOX_SUBSCRIPTION_ID }}
